CREATE DATA BASE imac;

CREATE TABLE vendors 
(vendor_id INTEGER ALWAYS GENERATED AS IDENTITY PRIMARY KEY , name VARCHAR(30) NOT NULL ,email varchar (30) NOT NULL UNIQUE, phone VARCHAR(30) , active BOOLEAN , create_at 
TIMESTAMP DEFAULT CUURRENT_TIMESTAMP);



CREATE TABLE users 
(user_id INTEGER ALWAYS GENERATED AS IDENTITY PRIMARY KEY , name VARCHAR(30) NOT NULL , email VARCHAR(30) NOT NULL UNIQUE , phone VARCHAR(30) ,rol VARCHAR(30)NOT NULL,active BOOLEAN , create_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP);



CREATE TABLE stock 

(item_id INTEGER ALWAYS GENERATED AS IDENTITY PRIMARY KEY , product_name varchar(30)NOT NULL, serial_number VARCHAR(30) NOT NULL, brand VARCHAR(30) NOT NULL , stock NUMERIC NOT NULL ,cost NUMERIC NOT NULL,owner VARCHAR(30) NOR NULL, location VARCHAR (30) , vendor INTERGER , FOREIGN KEY (vendor) REFERENCES vendors(vendor_id) , user_id INTEGER NOT NULL , FOREIGN KEY (user_id) REFERENCES users(user_id) , create_at TIMESTAMP DEFAULT CURRRENT_TIMESTAMP);
